### ISSUE TITLE
Avoid accessing implicit shared zip after forking

### ISSUE THREAD

**Issue by belldandyxtq** [chainer/chainerio#104]
**Problem statement**
Errors occur when multiple child processes read from an implicitly shared `ZipContainer` that is opened by parents process before forking

**How to reproduce**
```
import chainerio
from multiprocessing import Process

container = chainerio.open_as_container("dummy.zip")
# open a file inside the container to actually open the zip
# the zip will be implicitly shared after forking
with container.open("dummy_data") as f:
    f.read()

def func():
    # accessing the shared container
    with container.open("dummy_data") as f:
        f.read()

p1 = Process(target=func)
p2 = Process(target=func)
p1.start()
p2.start()

p1.join()
p2.join()
```
**Error Message**
```
Process Process-2:
Traceback (most recent call last):
  File "tianqi/.pyenv/versions/3.7.2/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "tianqi/.pyenv/versions/3.7.2/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "test.py", line 10, in func
    with container.open("dummy_data") as f:
  File "tianqi/repository/chainerio/chainerio/io.py", line 20, in wrapper
    errors, newline, closefd, opener)
  File "tianqi/repository/chainerio/chainerio/containers/zip.py", line 88, in open
    nested_file = self.zip_file_obj.open(file_path, "r")
  File "tianqi/.pyenv/versions/3.7.2/lib/python3.7/zipfile.py", line 1488, in open
    raise BadZipFile("Bad magic number for file header")
zipfile.BadZipFile: Bad magic number for file header
Process Process-1:
Traceback (most recent call last):
  File "tianqi/.pyenv/versions/3.7.2/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "tianqi/.pyenv/versions/3.7.2/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "test.py", line 11, in func
    f.read()
  File "tianqi/.pyenv/versions/3.7.2/lib/python3.7/zipfile.py", line 885, in read
    buf += self._read1(self.MAX_N)
  File "tianqi/.pyenv/versions/3.7.2/lib/python3.7/zipfile.py", line 975, in _read1
    data = self._decompressor.decompress(data, n)
zlib.error: Error -3 while decompressing data: invalid block type
```

**Root Cause**
As mentioned in the comments of the code, the root cause of this problem is that multiple child processes access to the same zip container that was opened by their parent process before forking. Since the underlying `fd` was copied when forking, while the actual file struct, which is stored outside the process heap, was not. Hence, all the child processes would read though the same `fd` under a shared zip and proceed the offset inside the shared `fd`, which cause all the processes to read broken data.

**Why do we need to prevent this is ChainerIO layer**
The problem can be eliminated if user avoid opening the container before forking. However,  such behavior can be hard to detect when the code gets complicated with classes framework.
For example:
```
import chainerio
from multiprocessing import Process


class SharedZip(object):
    def __init__(self, name_of_container):
        self.container = None
        self.name_of_container = name_of_container

    def open_container(self):
        self.container = chainerio.open_as_container(self.name_of_container)

    def read_file(self, file_in_container):
        if self.container is None:
            self.open_container()

        with self.container.open(file_in_container) as f:
            return f.read()



-------
# from codes uses other frameworks

self.shared_zip = SharedZip("dummy.zip")

-------
# then, called by some routines
read_some_data = self.shared_zip.read_file("dummy_data")

------
# later on, after forking
# in child processes

# error occurs here
read_other_data = self.shared_zip.read_file("other_dummy_data")
```

If we can prevent it from `ChainerIO` layer, then such problem can be eliminated completely without users' attention.

**Solution 1**
Detect that the process has been forked by comparing the `pid`:

1. Record the `pid` when opening the `zip_file_obj`
2. Check the current `pid` before every calls to the zip
3. Reopen the `zip_file_obj` if the `pid` do not match
4. Record the new `pid`

As the `pid` will be cached, the overhead to `os.getpid()` can be small 
http://man7.org/linux/man-pages/man2/getpid.2.html

**Solution 2**
Closing the `zip_file_obj` when forking

1.  in the call of `__getstate__ `
2. in the call of `__copy__`

The same solution might be applied to HDFS connection. 

**ToDo**

- [x] Add `pid` check to https://github.com/chainer/chainerio/blob/master/chainerio/containers/zip.py
(#105)
- [ ] Add `pid` check to https://github.com/chainer/chainerio/blob/master/chainerio/filesystems/hdfs.py

**Comment by belldandyxtq** [comment]
Close as we found that the second todo is not feasible from python side via pyarrow
